name: release
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build package
        run: yarn run build
      - name: Publish to NPM
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN : ${{ secrets.NPM_TOKEN }}
